### ISSUE TITLE
bytes -> bytearrays in read procedures

### ISSUE THREAD

**Issue by esel7353** [python-ivi/python-vxi11#8]
I had to transmit a lot of 128MB waveforms from my scope to the computer, which was extremely slow. After changing all the "bytes +=" parts in the read procedures to "bytearray.append", I was able to speed the process up by a factor of 10.

So I suggest applying these changes here too.

**Comment by sauerburger** [comment]
see github.com/sauerburger/pytohn-vxi11 for the updated version

**Comment by alexforencich** [comment]
Should be fixed now.
